### ISSUE TITLE
For Streaming (Content-Type: application/x-erlang-stream-binary), order in which stream header & actucal data is sent differs.

### ISSUE THREAD

**Issue by sujatha-mh** [neeraj9/egraphdb#9]
Streaming (Content-Type: application/x-erlang-stream-binary) is  handled by
- Keys of SelectedPath is sent as Stream Response Header.
- Each row of data is extracted using maps:fold on SelectedPath, then streamed using cowboy_req:stream_body()

Issue is due to maps processing being random, i.e maps:keys & fold process each key in random order.

Interesting Findings About maps:

> `StreamHeader = maps:keys(SelectedPaths). `
> 
> % returns keys in alphabetical order if map size =< 32
> % returns in random order if map size > 32

> ```
> Cols = maps:fold(fun(_AsName, JsonPath, AccIn3) ->
>              [nested:get(JsonPath, Info, null) | AccIn3]
>                     end, [], SelectedPaths),
> ```
> %% returns Cols in reverse order of keys, if map size =< 32
> %% returns Cols in same order as keys, if map size > 32

Try It out to validate:
```
%% for map size 32
List1 = [{C, <<"somevalue">>} || C <- lists:seq(1,32)].
Map1 = maps:from_list(List1).
Keys1 = maps:keys(Map1).
maps:fold(fun(X, Y, Acc) -> io:format("~p, ",[X]) end, [], Map1).

%% for map size 32
List2 = [{C, <<"somevalue">>} || C <- lists:seq(1,33)].
Map2 = maps:from_list(List2).
Keys2 = maps:keys(Map2).
maps:fold(fun(X, Y, Acc) -> io:format("~p, ",[X]) end, [], Map2).
```

**Comment by neeraj9** [comment]
Wow!! This is interesting to know.

**Comment by neeraj9** [comment]
Ah! I recollect the logic now. The older code did not assert that the header fields are in order. It doesn't have to be sorted. The only assertion made here is that the header must match the values themselves. If you notice that when the size of the map is greater than 32 (as you indicated) the keys are in random order (non-sorted), but the order of maps:keys/1 and maps:fold/3 is the same. So, header and values will ultimately match.

There is a bug though, which is that Cols is reverse of what it is supposed to be due to list comprehension. One of the fix can be (NOT BEST):

```
Serialized = encode_erlang_stream_binary(lists:reverse(Cols))
```
A better fix would be to reverse the header instead which will happen only once.

```
StreamHeader = lists:reverse(maps:keys(SelectedPaths)),
```

Try this out (based on your example).
```
24> List2 = [{C, C} || C <- lists:seq(1,33)].              
[{1,1},
 {2,2},
 {3,3},
 {4,4},
 {5,5},
 {6,...},
 {...}|...]
25> f(Map2).
ok
26> Map2 = maps:from_list(List2).
#{20 => 20,17 => 17,25 => 25,13 => 13,8 => 8,7 => 7,1 => 1,
  32 => 32,3 => 3,6 => 6,2 => 2,33 => 33,10 => 10,9 => 9,
  19 => 19,14 => 14,5 => 5,18 => 18,31 => 31,22 => 22,
  29 => 29,21 => 21,27 => 27,24 => 24,30 => 30,23 => 23,
  28 => 28,16 => 16,4 => 4,...}
27> Keys2 = maps:keys(Map2).
[11,26,15,20,17,25,13,8,7,1,32,3,6,2,33,10,9,19,14,5,18,31,
 22,29,21,27,24,30,23|...]
28> f(SelectedPaths).
ok
29> SelectedPaths = Map2.                    
#{20 => 20,17 => 17,25 => 25,13 => 13,8 => 8,7 => 7,1 => 1,
  32 => 32,3 => 3,6 => 6,2 => 2,33 => 33,10 => 10,9 => 9,
  19 => 19,14 => 14,5 => 5,18 => 18,31 => 31,22 => 22,
  29 => 29,21 => 21,27 => 27,24 => 24,30 => 30,23 => 23,
  28 => 28,16 => 16,4 => 4,...}
30> StreamHeader = maps:keys(SelectedPaths). 
[11,26,15,20,17,25,13,8,7,1,32,3,6,2,33,10,9,19,14,5,18,31,
 22,29,21,27,24,30,23|...]
33> Cols = maps:fold(fun(_AsName, JsonPath, AccIn3) ->
33>              [JsonPath | AccIn3]
33>                     end, [], SelectedPaths).
[12,4,16,28,23,30,24,27,21,29,22,31,18,5,14,19,9,10,33,2,6,
 3,32,1,7,8,13,25,17|...]
34> lists:reverse(Cols).
[11,26,15,20,17,25,13,8,7,1,32,3,6,2,33,10,9,19,14,5,18,31,
 22,29,21,27,24,30,23|...]
35> SelectedPaths.
#{20 => 20,17 => 17,25 => 25,13 => 13,8 => 8,7 => 7,1 => 1,
  32 => 32,3 => 3,6 => 6,2 => 2,33 => 33,10 => 10,9 => 9,
  19 => 19,14 => 14,5 => 5,18 => 18,31 => 31,22 => 22,
  29 => 29,21 => 21,27 => 27,24 => 24,30 => 30,23 => 23,
  28 => 28,16 => 16,4 => 4,...}
36> Keys2.
[11,26,15,20,17,25,13,8,7,1,32,3,6,2,33,10,9,19,14,5,18,31,
 22,29,21,27,24,30,23|...]
37> Keys2 = lists:reverse(Cols).
[11,26,15,20,17,25,13,8,7,1,32,3,6,2,33,10,9,19,14,5,18,31,
 22,29,21,27,24,30,23|...]

```

**Comment by neeraj9** [comment]
PLEASE move to https://github.com/egraphdb/egraphdb and raise pull request there going forward.

**Comment by sujatha-mh** [comment]
maps:fold works differently in OTP 18 & OTP 21.

StreamHeader = lists:reverse(maps:keys(SelectedPaths)),

This fix will not work on OTP 21. Please validate my observation.

![otp18](https://user-images.githubusercontent.com/7299037/57998640-ffdda900-7aef-11e9-8443-3f175116ea51.png)
![otp21](https://user-images.githubusercontent.com/7299037/57998641-ffdda900-7aef-11e9-9f22-def87687141b.png)

**Comment by sujatha-mh** [comment]
As per internal implementation:
Before OTP 20, for all map size, map was sorted based on key and stored.

Later was changed based on size of the map. 
It still sorts and store for map size lesser than or equal to 32

taken from OTP codebase : 
https://github.com/erlang/otp/blob/OTP-21.0/erts/emulator/beam/erl_map.c
Line : 236

MAP_SMALL_MAP_LIMIT = 32
`if (size > MAP_SMALL_MAP_LIMIT) {
            BIF_RET(hashmap_from_validated_list(BIF_P, BIF_ARG_1, size));
        } else {
            BIF_RET(flatmap_from_validated_list(BIF_P, BIF_ARG_1, size));
        }
`

**Comment by neeraj9** [comment]
This is strange. It is odd that the order of traversal in maps:keys/1 is different from maps:fold/3. If we have to workaround this as per your change then it will incur a performance penalty. It would be important to understand the difference in traversal though before giving up on this.

**Comment by neeraj9** [comment]
Haha! The Erlang core team is playing with maps in a good way though. @sujatha-mh your example will work differently for before and after OTP 21.

For OTP-21 you don’t have to reverse the order of maps:keys/1 for maps with more than 32 elements. This is probably to optimize maps:keys/1 and match the maps:fold/1 (with accumulator) which we are using for bigger maps. Smaller maps are not stored as maps in memory hence keys being in sorted order. This is largely to optimize maps which are smaller in size and make most of the application code run faster.

I will summarize my findings but the moot point is now that can we rely on the order of traversal used by maps:keys/1 and maps:fold/3.

**Summary**
> Equality is maps:keys(M) =:= maps:fold(fun(K, _, A) -> [K | A] end, [], M)
> ReverseEquality is lists:reverse(maps:keys(M)) =:= maps:fold(fun(K, _, A) -> [K | A] end, [], M)

Notice that for OTP 21 onwards the order of maps:keys/1 is same as when we use accumulator over maps:fold/3.

| OTP |  Size | Equality | ReverseEquality |
| --- | --- | --- | --- |
| 19 | 10 | false | true |
| 19 | 32 | false | true |
| 19 | 34 | false | true |
| 20 | 10 | false | true |
| 20 | 32 | false | true |
| 20 | 34 | false | true |
| 21 | 10 | false | true |
| 21 | 32 | false | true |
| 21 | 34 | **true** | false |
| 22 | 10 | false | true |
| 22 | 32 | false | true |
| 22 | 34 | **true** | false |


For OTP-21:
* maps:size(M) > 32
  * maps:keys(M) =:= maps:fold(fun(K, _, AccIn) -> [K | AccIn] end, [], M).
* maps:size(M2) =< 32
  * lists:reverse(maps:keys(M2)) =:= maps:fold(fun(K, _, AccIn) -> [K | AccIn] end, [], M2).

**Detailed Analysis**:

*Emulator "8.3.5.7", OTP Release is "19"*
```
esl-erlang_19.3.6.13-1~ubuntu~xenial_amd64.deb
size=10, Equality=false, ReverEquality=true
size=32, Equality=false, ReverEquality=true
size=34, Equality=false, ReverEquality=true
```

Emulator "9.0", OTP Release is "20"
```
esl-erlang_20.0-1~ubuntu~xenial_amd64.deb
size=10, Equality=false, ReverEquality=true
size=32, Equality=false, ReverEquality=true
size=34, Equality=false, ReverEquality=true
```

*Emulator "10.2.3", OTP Release is "21"*
```
esl-erlang_21.2.4-1~ubuntu~xenial_amd64.deb
size=10, Equality=false, ReverEquality=true
size=32, Equality=false, ReverEquality=true
size=34, Equality=true, ReverEquality=false
```

*Emulator "10.4", OTP Release is "22"*
```
esl-erlang_22.0.1-1~ubuntu~xenial_amd64.deb
size=10, Equality=false, ReverEquality=true
size=32, Equality=false, ReverEquality=true
size=34, Equality=true, ReverEquality=false
```

The script to generate the above output is as follows:
https://gist.github.com/neeraj9/cf8639cce5de2c3a6a0cf9c9ffa4383b

**Comment by neeraj9** [comment]
I believe it will be tricky to rely on internal implementation of maps when the order of maps:keys/1 may not align with maps:fold/3 across OTP versions.

@sujatha-mh How about trying this out instead as a fix, which I have also indicated in PR https://github.com/sujatha-mh/egraphdb/commit/292e05fd5dc2dbae8bb247cd1e81f42cd90f4024

```
FunGetMatchingMapKeys = fun(X) ->
    L = [{C, C} || C <- lists:seq(1, maps:size(X))],
    M = maps:from_list(L),
    A1 = maps:keys(M),
    B1 = maps:fold(fun(K, _, AccIn) -> [K | AccIn] end, [], M),
    Equality = A1 =:= B1,
    ReverseEquality = lists:reverse(A1) =:= B1,
    case {Equality, ReverseEquality} of
        {true, false} -> maps:keys(X);
        {false, true} -> lists:reverse(maps:keys(X))
    end
end,

StreamHeader = FunGetMatchingMapKeys(SelectedPaths)
```

**Comment by sujatha-mh** [comment]
yes it is tricky to depend on maps for ordered processing. but if we convert maps to list of tuples, and use that for ordered traversal, will that not be better?
```
%% for headers
SelectedPathsList = maps:to_list(SelectedPaths),
StreamHeader = [element(1, X) || X <- SelectedPathsList],
```
```
%%for cols
Cols = lists:foldl(fun({_AsName, JsonPath}, AccIn3) ->
                               [nested:get(JsonPath, Info, null) | AccIn3]
                                       end, [], SelectedPathsList),
```

Below given is the simple performance test result on both the approaches. 

| Map SIze  | Equality Check (ms) | to_list processing (ms)|
| ------------- | ------------- |------------------------------|
| 32 | 1  | 1 |
| 10,000  |  72  | 57 |
| 1,00,000 | 938 | 585 |
| 10,00,000 | 8078 | 5979|
| 1,00,00,000 | 87635 | 69473 | 


Code to generate the above result.
```
FunGetMatchingMapKeys = fun(X) ->
    L = [{C, C} || C <- lists:seq(1, maps:size(X))],
    M = maps:from_list(L),
    A1 = maps:keys(M),
    B1 = maps:fold(fun(K, _, AccIn) -> [K | AccIn] end, [], M),
    Equality = A1 =:= B1,
    ReverseEquality = lists:reverse(A1) =:= B1,
    case {Equality, ReverseEquality} of
        {true, false} -> maps:keys(X);
        {false, true} -> lists:reverse(maps:keys(X))
    end
end.

ProcessWithMap = fun(SelectedPaths1) ->
    T0 = erlang:monotonic_time(milli_seconds),
    StreamHeader = FunGetMatchingMapKeys(SelectedPaths1),
    Cols = maps:fold(fun(_AsName, JsonPath, AccIn3) -> [JsonPath | AccIn3] end, [], SelectedPaths1),
    T1 = erlang:monotonic_time(milli_seconds),
    T1 - T0
end.

ProcessWithTupleList = fun(SelectedPaths1) -> 
    T0 = erlang:monotonic_time(milli_seconds), 
    SelectedPathsList = maps:to_list(SelectedPaths1), 
    StreamHeader = [element(1, X) || X <- SelectedPathsList], 
    Cols = lists:foldr(fun({_AsName, JsonPath}, AccIn3) -> [JsonPath | AccIn3] end, [], SelectedPathsList), 
    T1 = erlang:monotonic_time(milli_seconds), 
    T1- T0 
end.

ProcessWithMap( maps:from_list([{C, C} || C <- lists:seq(1,10000)])).
ProcessWithTupleList( maps:from_list([{C, C} || C <- lists:seq(1,10000)])).

ProcessWithMap( maps:from_list([{C, C} || C <- lists:seq(1,100000)])).
ProcessWithTupleList( maps:from_list([{C, C} || C <- lists:seq(1,100000)])).

ProcessWithMap( maps:from_list([{C, C} || C <- lists:seq(1,1000000)])).
ProcessWithTupleList( maps:from_list([{C, C} || C <- lists:seq(1,1000000)])).

ProcessWithMap( maps:from_list([{C, C} || C <- lists:seq(1,10000000)])).
ProcessWithTupleList( maps:from_list([{C, C} || C <- lists:seq(1,10000000)])).
```

**Comment by neeraj9** [comment]
@sujatha-mh I unnecessarily complicated the alternative. After think with a fresh perspective the solution is actually very simple. Note that in your suggestion the assumption is that maps:to_list/1 has the same traversal order as maps:fold/3. This may not be true in the future.

How about this?
‘’’
StreamHeader = maps:fold(fun(K, _, AccIn) -> [K | AccIn] end, [], SelectedPaths)
‘’’

**Comment by sujatha-mh** [comment]
This works perfectly

**Comment by neeraj9** [comment]
@sujatha-mh Thanks for following through the discussion and closing the pull request.
